# Generated by Django 6.0.7 on 2026-09-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_service_tags_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
    ]
