# Generated by Django 6.0.7 on 2026-09-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_notification_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicegallery',
            name='service',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ServiceGallery',
        ),
    ]
