# Generated by Django 6.0.7 on 2026-09-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_address_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
