# Generated by Django 6.0.7 on 2026-09-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='seen',
        ),
    ]
