# Generated by Django 6.0.7 on 2026-09-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_notifications_seen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
