# Generated by Django 6.0.7 on 2026-09-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_delete_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
